{% set name = "click-default-group" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9560e8e8dfa44b3562fbc9425042a0fd6d21956fcc2db0077f63f34253ab904

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - click

test:
  imports:
    - click_default_group
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/click-contrib/click-default-group
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extends click.Group to invoke a command without explicit subcommand name.'
  description: |
    Extends click.Group to invoke a command without explicit subcommand name.
    DefaultGroup is a sub class of click.Group. But it invokes a default subcommand 
    instead of showing a help message when a subcommand is not passed.

extra:
  recipe-maintainers:
    - ericmjl
    - mariusvniekerk
    - thewchan
