travis:
  secure:
    BINSTAR_TOKEN: JIhhcTuNzLqULpuz1CnxcZ/4DdLlQn+uA3WniJiIq6IBbMNJszaiiDfwC54j0bzEVHj4RJlJRQ38XboxyFDAfG7n/GGMQu5C5IsFrUv4F+dyMKtjuuQOPyn5NZZaDQaOF/iIG2YNKXZiw5/I5B17rrTBugxis2RjvRwoM8OmkwZ/QmBhyZTIauifCG2nkuAgVZg14G+ecuInBnvOElNjb7QovRG7RhBySBRjb4WOeNCrGNx3go8ufzbBAZqnL4oLpL3JKQO5aJqqQtBitQ8xwW/ZR9i9R+XaEKvJBVcQYEr/RgZ0k3hXr0Ky47yWpCeWKel3e9+kVxVtXyQwxSvLOlzEAnEOoxEvpIWrJJMazztpVQRqOIBuz/iyBrseJEwkqiplOAKdzR975m7x5BnTExWppLDUQkcS39j4r6E7BQjCszWYUsOJGR4MtAQlCzJadQDDzWxLwcGJ3fVkZxXC1n0MayB4fPBkMMVxYwkA1npF1x+p06ef1Phwaa1DJ2306fWp1o+o0dLjgzVgumsVU7EEq+qdEH/raa3cFR7OelWk13fs3u1ah50klvmACMg1z4zcPpzDoCN8sXYT9ujTvJY5zFrGzPkK6DnFuoQ38pjf8zKqtSOn+M2hYqeU1WefrcCbWYGFBSlrEipTAoxLH1W6h85CBaS6i9PuHxRALyA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
